version: '3.8'
services:
  app:
    image: node:latest
    container_name: toko_online
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3001:3000
    depends_on:
      - database
    command: npm run start:dev

  # Database
  database:
    container_name: database_c
    image: 'postgres:12'
    env_file:
      - .env
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: {}
